filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: unix:///var/run/docker.sock
      - drop_event.when.not.or:
          - contains.container.name: commercehub-

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      when.regexp.message: "^\\{"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "commercehub-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.template.name: "commercehub-logs"
setup.template.pattern: "commercehub-logs-*"
setup.ilm.enabled: false

logging.level: info
logging.to_files: false
logging.to_stderr: true
